version: '3'

services:
  spring-app:
    image: ezui7/nejd:springtest
    ports:
      - "8089:8089"
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql:latest
    ports:
      - "3307:3307"
    environment:
      - MYSQL_DATABASE=examBedouiNejd2
      - MYSQL_ROOT_PASSWORD=123456789
