version: '3'

services:
  spring-app:
    image: ezui7/nejd:springtest
    ports:
      - "8090:8089"
    depends_on:
      - mysql-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3307/examBedouiNejd2
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456789

  mysql-db:
    image: mysql:latest
    ports:
      - "3307:3307"
    environment:
      - MYSQL_DATABASE=examBedouiNejd2
      - MYSQL_ROOT_PASSWORD=123456789
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456789
